### ISSUE TITLE
PS3 PUP unpacker opens PARAM.SFO editor

### ISSUE THREAD

**Issue by mirh** [SvenGDK/PS-Multi-Tools#1]
https://github.com/SvenGDK/PS-Multi-Tools/blob/4ccb33d5ad986fc620308fa5a44f48ee35d06c09/PS%20Multi%20Tools/NewMainWindow.xaml.vb#L272L275

**Comment by SvenGDK** [comment]
Thanks, this is fixed now in the latest release.
