### ISSUE TITLE
Missing DLLs

### ISSUE THREAD

**Issue by ccfman2004** [SvenGDK/PS-Multi-Tools#3]
pkg-merge.exe does not work as it says there are missing .dll files.

```
vcruntime140D.dll
msvcp140d.dll
ucrtbased.dll
```

Other CLI programs in the tools folder also complain about missing DLL files like zlib1.dll.

Upon adding the 3 missing DLL files pkg-merge.exe now gives another runtime error.

<img width="644" alt="Screen Shot 2024-01-14 at 8 04 10 PM" src="https://github.com/SvenGDK/PS-Multi-Tools/assets/79392/055acabc-21ad-4262-9638-326af9088a5b">

Don't know what else to do.

I already have the MS C++ Runtime libraries installed but that doesn't fix the issues.

**Comment by SvenGDK** [comment]
Open this issue here:
https://github.com/aldo-o/pkg-merge
